### PR TITLE
Adds dry-python to Python section

### PR DESCRIPTION
**Pull request by sobolevn**
`dry-python` consists of several independent libraries. Each of them serves a very specific purpose.
And the whole idea is based on providing better tooling for business logic and domain driven design.

Link: https://github.com/dry-python

### CODE REVIEW

**Comment by sobolevn** [comment]
@heynickc friendly ping

**Comment by wtjones** [comment]
Where would I find the documentation? I figured stories https://dry-python.org/#stories was the main DDD aspect but all I could find was the example on the front page.

**Comment by witek1902** [comment]
@sobolevn I can't find how this is related to DDD. Could you give us a more detailed description?

**Comment by emacsway** [comment]
> I can't find how this is related to DDD.

@witek1902 , I know that. That is excellent for functional DDD. You can find more info here:
- https://fsharpforfunandprofit.com/rop/
and here:
- https://fsharpforfunandprofit.com/books/#domain-modeling-made-functional-ebook-and-paper

**Pull request merged**
